### PR TITLE
Remove full path from certain commands in ds

### PR DESCRIPTION
**Pull request by AlarmingCow**
`grep` and `readlink` are in `/usr/bin/` rather than `/bin/` on OS X. `cp` is in `/bin/` but I figured I'd be consistent.

### CODE REVIEW

**Comment by AlarmingCow** [comment]
@briehman Any particular reason you did it that way? Don't want to screw anything up for you Linux-havers.

**Comment by briehman** [comment]
I kept the absolute path convention as an old habit to ensure PATH manipulation wouldn't get an unsuspecting version. Most likely not necessary in this case. I am surprised that those aren't available in /bin/ on OS X but I'm also surprised I don't have links to the /bin/ versions in /usr/bin/ under Ubuntu! Seems like the absolute paths are more trouble than they're worth so I'm happy to get rid of them. Thanks!

**Comment by nprbsg** [comment]
@briehman I'm /(un)?surprised/ that Apple would so blatantly violate the POSIX FSS.

**Comment by cstroe** [comment]
Might have something to do with being OSX being BSD derived.  BSD follows a different layout, due to design and heritage.

**Pull request merged**
